import esbuild from 'esbuild';
import esbuildSvelte from 'esbuild-svelte';
import { sveltePreprocess } from 'svelte-preprocess';
import { configDotenv } from 'dotenv';
import process from 'process';
import { mkdirSync } from 'node:fs';
import { builtinModules } from 'node:module';
import path from 'node:path';

configDotenv();

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';

const outDir = process.env.LAVA_PLUGIN_DIR
    ? path.resolve(process.env.LAVA_PLUGIN_DIR)
    : path.resolve('.');
const outfile = path.join(outDir, 'main.js');
mkdirSync(outDir, { recursive: true });

const context = await esbuild.context({
    banner: {
        js: banner,
    },
    entryPoints: ['src/main.ts'],
    bundle: true,
    external: [
        'obsidian',
        'electron',
        '@codemirror/autocomplete',
        '@codemirror/collab',
        '@codemirror/commands',
        '@codemirror/language',
        '@codemirror/lint',
        '@codemirror/search',
        '@codemirror/state',
        '@codemirror/view',
        '@lezer/common',
        '@lezer/highlight',
        '@lezer/lr',
        ...builtinModules,
    ],
    mainFields: ['svelte', 'browser', 'module', 'main'],
    conditions: ['svelte', 'browser'],
    format: 'cjs',
    target: 'es2021',
    logLevel: 'info',
    sourcemap: prod ? false : 'inline',
    treeShaking: true,
    define: {
        __LAVA_SUPABASE_URL__: JSON.stringify(process.env.LAVA_SUPABASE_URL ?? ''),
        __LAVA_SUPABASE_ANON_KEY__: JSON.stringify(process.env.LAVA_SUPABASE_ANON_KEY ?? ''),
        __LAVA_API_BASE_URL__: JSON.stringify(process.env.LAVA_API_BASE_URL ?? ''),
    },
    outfile,
    minify: prod,
    plugins: [
        esbuildSvelte({
            compilerOptions: { css: 'injected' },
            preprocess: sveltePreprocess(),
        }),
    ],
});

if (prod) {
    await context.rebuild();
    process.exit(0);
} else {
    await context.watch();
}
